"""Verification Node - Validates generated code.

Four verification checkpoints:
A. Syntax Check - Python ast.parse validation
B. Import Check - Verify all imports resolve
C. Pytest Collection - pytest --collect-only
D. Test Execution - Actually run the tests and verify they pass
"""

import ast
import importlib.util
import logging
import os
import re
import subprocess
import sys
import tempfile
import time
from typing import Dict, List, Any, Tuple, Optional

from ..models.state import AgentState
from ..models.schemas import CheckpointStatus, CheckpointResult, VerificationResults
from ..tools.code_executor import run_pytest

logger = logging.getLogger(__name__)


def _check_syntax(code: str, filepath: str) -> Tuple[bool, str]:
    """
    Check Python syntax using ast.parse.
    
    Args:
        code: Python code string
        filepath: File path (for error messages)
        
    Returns:
        Tuple of (success, error_message)
    """
    try:
        ast.parse(code)
        return True, ""
    except SyntaxError as e:
        return False, f"Line {e.lineno}: {e.msg}"


def checkpoint_a_syntax(generated_files: Dict[str, str]) -> CheckpointResult:
    """
    Checkpoint A: Validate Python syntax for all generated files.
    
    Args:
        generated_files: Dict of filepath -> code content
        
    Returns:
        CheckpointResult with syntax validation results
    """
    logger.info("Running Checkpoint A: Syntax Validation...")
    
    files_checked = []
    files_passed = []
    files_failed = []
    errors = {}
    
    for filepath, code in generated_files.items():
        # Only check Python files
        if not filepath.endswith('.py'):
            continue
        
        files_checked.append(filepath)
        
        success, error = _check_syntax(code, filepath)
        
        if success:
            files_passed.append(filepath)
            logger.debug(f"  ✓ {filepath}")
        else:
            files_failed.append(filepath)
            errors[filepath] = error
            logger.warning(f"  ✗ {filepath}: {error}")
    
    status = CheckpointStatus.PASSED if not files_failed else CheckpointStatus.FAILED
    
    return CheckpointResult(
        checkpoint_name="A",
        checkpoint_description="Python Syntax Validation",
        status=status,
        files_checked=files_checked,
        files_passed=files_passed,
        files_failed=files_failed,
        errors=errors
    )


def checkpoint_b_imports(generated_files: Dict[str, str]) -> CheckpointResult:
    """
    Checkpoint B: Verify imports can be resolved.
    
    Note: This checks standard library and installed packages only.
    Internal imports between generated files are assumed valid.
    
    Args:
        generated_files: Dict of filepath -> code content
        
    Returns:
        CheckpointResult with import validation results
    """
    logger.info("Running Checkpoint B: Import Validation...")
    
    files_checked = []
    files_passed = []
    files_failed = []
    errors = {}
    
    # Known internal modules (generated by us)
    internal_modules = {"pages", "flows", "tests"}
    
    for filepath, code in generated_files.items():
        if not filepath.endswith('.py'):
            continue
        
        files_checked.append(filepath)
        file_errors = []
        
        try:
            tree = ast.parse(code)
            
            for node in ast.walk(tree):
                # Check import statements
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        module_name = alias.name.split('.')[0]
                        if module_name not in internal_modules:
                            if not _can_import(module_name):
                                file_errors.append(f"Cannot import '{alias.name}'")
                
                # Check from ... import statements
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        module_name = node.module.split('.')[0]
                        if module_name not in internal_modules:
                            if not _can_import(module_name):
                                file_errors.append(f"Cannot import from '{node.module}'")
            
            if file_errors:
                files_failed.append(filepath)
                errors[filepath] = "; ".join(file_errors)
                logger.warning(f"  ✗ {filepath}: {errors[filepath]}")
            else:
                files_passed.append(filepath)
                logger.debug(f"  ✓ {filepath}")
                
        except SyntaxError:
            # Already caught in checkpoint A
            files_passed.append(filepath)
    
    status = CheckpointStatus.PASSED if not files_failed else CheckpointStatus.FAILED
    
    return CheckpointResult(
        checkpoint_name="B",
        checkpoint_description="Import Resolution",
        status=status,
        files_checked=files_checked,
        files_passed=files_passed,
        files_failed=files_failed,
        errors=errors
    )


def _can_import(module_name: str) -> bool:
    """Check if a module can be imported."""
    try:
        spec = importlib.util.find_spec(module_name)
        return spec is not None
    except (ModuleNotFoundError, ValueError):
        return False


def checkpoint_c_collect(
    generated_files: Dict[str, str],
    output_dir: str
) -> CheckpointResult:
    """
    Checkpoint C: Run pytest --collect-only to verify test discovery.
    
    Writes files to temp directory and runs pytest collection.
    
    Args:
        generated_files: Dict of filepath -> code content
        output_dir: Output directory to write files
        
    Returns:
        CheckpointResult with collection results
    """
    logger.info("Running Checkpoint C: Pytest Collection...")
    
    files_checked = []
    files_passed = []
    files_failed = []
    errors = {}
    
    # Write files to output directory
    for filepath, code in generated_files.items():
        full_path = os.path.join(output_dir, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(code)
        
        files_checked.append(filepath)
    
    # Run pytest --collect-only
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pytest", "--collect-only", "-q"],
            cwd=output_dir,
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode == 0:
            # Parse collected tests
            output_lines = result.stdout.strip().split('\n')
            test_count = 0
            for line in output_lines:
                if '::test_' in line or line.strip().startswith('<Function'):
                    test_count += 1
            
            logger.info(f"  Collected {test_count} tests")
            files_passed = files_checked
            
        else:
            # Collection failed
            error_msg = result.stderr or result.stdout
            errors["collection"] = error_msg[:500]  # Truncate long errors
            files_failed = [f for f in files_checked if f.endswith('.py') and 'test' in f]
            files_passed = [f for f in files_checked if f not in files_failed]
            logger.warning(f"  Collection failed: {error_msg[:200]}")
            
    except subprocess.TimeoutExpired:
        errors["collection"] = "Pytest collection timed out"
        files_failed = files_checked
        logger.error("  Collection timed out")
    except Exception as e:
        errors["collection"] = str(e)
        files_failed = files_checked
        logger.error(f"  Collection error: {e}")
    
    status = CheckpointStatus.PASSED if not files_failed else CheckpointStatus.FAILED
    
    return CheckpointResult(
        checkpoint_name="C",
        checkpoint_description="Pytest Collection",
        status=status,
        files_checked=files_checked,
        files_passed=files_passed,
        files_failed=files_failed,
        errors=errors
    )


def _extract_error_type(error_line: str) -> Optional[str]:
    """Extract error type from pytest error line."""
    error_patterns = [
        r'AttributeError: (.+)',
        r'AssertionError: (.+)',
        r'NameError: (.+)',
        r'TypeError: (.+)',
        r'ImportError: (.+)',
        r'TimeoutException: (.+)',
        r'NoSuchElementException: (.+)',
        r'WebDriverException: (.+)',
        r'TimeoutError: (.+)'
    ]
    
    for pattern in error_patterns:
        match = re.search(pattern, error_line)
        if match:
            return match.group(0)
    return None


def checkpoint_d_execution(
    generated_files: Dict[str, str],
    output_dir: str,
    timeout: int = 120
) -> CheckpointResult:
    """
    Checkpoint D: Actually run the tests and verify they pass.
    
    This catches runtime errors like:
    - AttributeError (wrong method names)
    - AssertionError (test logic failures)
    - Import errors at runtime
    - Selenium/WebDriver issues
    
    Args:
        generated_files: Dict of filepath -> code content
        output_dir: Output directory with test files
        timeout: Max execution time in seconds
        
    Returns:
        CheckpointResult with test execution results
    """
    logger.info("Running Checkpoint D: Test Execution...")
    start_time = time.time()
    
    files_checked = []
    files_passed = []
    files_failed = []
    errors = {}
    
    # Ensure all files are written
    for filepath, code in generated_files.items():
        full_path = os.path.join(output_dir, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(code)
        if filepath.endswith('.py'):
            files_checked.append(filepath)
    
    # Run pytest
    try:
        result = run_pytest(
            test_dir=output_dir,
            collect_only=False,
            timeout=timeout
        )
        
        duration = time.time() - start_time
        
        if result["success"] and result["failed"] == 0:
            # All tests passed!
            logger.info(f"  ✓ All {result['passed']} tests passed in {duration:.2f}s")
            files_passed = files_checked
            status = CheckpointStatus.PASSED
            
            return CheckpointResult(
                checkpoint_name="D",
                checkpoint_description="Test Execution",
                status=status,
                files_checked=files_checked,
                files_passed=files_passed,
                files_failed=files_failed,
                errors=errors,
                duration_seconds=duration,
                metadata={
                    "tests_passed": result.get("passed", 0),
                    "tests_failed": result.get("failed", 0),
                    "tests_errors": result.get("errors", 0)
                }
            )
        else:
            # Tests failed - parse errors
            status = CheckpointStatus.FAILED
            output = result["output"]
            
            logger.warning(f"  ✗ {result['failed']} tests failed, {result['passed']} passed")
            
            # Parse pytest output to extract failures
            # Improved parsing to handle various pytest output formats
            current_test = None
            current_file = None
            error_lines = []
            in_traceback = False
            error_type = None
            
            lines = output.split('\n')
            i = 0
            while i < len(lines):
                line = lines[i]
                
                # Detect test name and file (multiple formats)
                # Format 1: "tests/test_saucedemo.py::test_name FAILED"
                # Format 2: "FAILED tests/test_saucedemo.py::test_name"
                # Format 3: "test_name FAILED"
                if ('::test_' in line or '::Test' in line) and ('FAILED' in line or 'ERROR' in line):
                    # Extract file and test name
                    test_match = re.search(r'([^/\s]+\.py)::([^\s]+)', line)
                    if test_match:
                        current_file = test_match.group(1)
                        current_test = test_match.group(2)
                        error_lines = []
                        in_traceback = False
                        error_type = None
                        logger.debug(f"Found failed test: {current_file}::{current_test}")
                
                # Detect error type (look for "E   " lines)
                if line.startswith('E   ') and not in_traceback:
                    extracted_type = _extract_error_type(line)
                    if extracted_type:
                        error_type = extracted_type
                        in_traceback = True
                        error_lines.append(line.strip())
                        logger.debug(f"Found error type: {error_type}")
                
                # Collect traceback
                if in_traceback:
                    if line.startswith('E   ') or (line.startswith(' ') and len(line.strip()) > 0 and not line.strip().startswith('=')):
                        error_lines.append(line.strip())
                    elif line.strip() and not line.startswith('=') and not line.startswith('-') and 'FAILED' not in line:
                        # End of traceback - save the error
                        if current_file and error_lines:
                            # Limit error message length
                            error_msg = '\n'.join(error_lines[:20])
                            
                            # Map to actual source file (test file or page file)
                            # If error is in a page object, find that file
                            source_file = current_file
                            for error_line in error_lines:
                                # Check if error references a page file
                                # Pattern: File "/path/to/pages/login_page.py", line X
                                page_match = re.search(r'File "([^"]+(?:pages|flows)/[^"]+\.py)"', error_line)
                                if page_match:
                                    full_path = page_match.group(1)
                                    # Extract relative path from output_dir
                                    if output_dir in full_path:
                                        source_file = full_path.replace(output_dir + '/', '')
                                    else:
                                        # Extract just the relative path
                                        # Try to find pages/ or flows/ in path
                                        path_parts = full_path.split('/')
                                        if 'pages' in path_parts or 'flows' in path_parts:
                                            idx = max(path_parts.index('pages') if 'pages' in path_parts else -1,
                                                    path_parts.index('flows') if 'flows' in path_parts else -1)
                                            if idx >= 0:
                                                source_file = '/'.join(path_parts[idx:])
                                    logger.debug(f"Mapped error to source file: {source_file}")
                                    break
                            
                            if source_file not in errors:
                                errors[source_file] = []
                            
                            error_summary = f"{current_test}: {error_type or 'Error'}"
                            errors[source_file].append(f"{error_summary}\n{error_msg}")
                            logger.debug(f"Added error for {source_file}: {error_summary[:50]}")
                        
                        in_traceback = False
                        error_lines = []
                
                i += 1
            
            # Handle any remaining error in traceback
            if in_traceback and current_file and error_lines:
                error_msg = '\n'.join(error_lines[:20])
                source_file = current_file
                for error_line in error_lines:
                    page_match = re.search(r'File "([^"]+(?:pages|flows)/[^"]+\.py)"', error_line)
                    if page_match:
                        full_path = page_match.group(1)
                        if output_dir in full_path:
                            source_file = full_path.replace(output_dir + '/', '')
                        else:
                            path_parts = full_path.split('/')
                            if 'pages' in path_parts or 'flows' in path_parts:
                                idx = max(path_parts.index('pages') if 'pages' in path_parts else -1,
                                        path_parts.index('flows') if 'flows' in path_parts else -1)
                                if idx >= 0:
                                    source_file = '/'.join(path_parts[idx:])
                        break
                
                if source_file not in errors:
                    errors[source_file] = []
                error_summary = f"{current_test or 'Unknown'}: {error_type or 'Error'}"
                errors[source_file].append(f"{error_summary}\n{error_msg}")
            
            # Convert error lists to strings for storage
            for filepath, error_list in errors.items():
                if isinstance(error_list, list):
                    errors[filepath] = '\n\n'.join(error_list)
            
            # If we couldn't parse, use raw output
            if not errors:
                logger.warning("Could not parse pytest errors, using raw output")
                errors["test_execution"] = output[:2000]  # Truncate long output
            else:
                logger.info(f"Parsed {len(errors)} files with errors: {list(errors.keys())}")
            
            files_failed = list(errors.keys())
            files_passed = [f for f in files_checked if f not in files_failed]
            
            # Ensure status is FAILED if there are errors or test failures
            if errors or result.get("failed", 0) > 0 or result.get("errors", 0) > 0:
                status = CheckpointStatus.FAILED
                logger.warning(f"  ✗ Checkpoint D FAILED: {result.get('failed', 0)} tests failed, {result.get('passed', 0)} passed")
            else:
                status = CheckpointStatus.PASSED
                logger.info(f"  ✓ Checkpoint D PASSED: {result.get('passed', 0)} tests passed")
            
            return CheckpointResult(
                checkpoint_name="D",
                checkpoint_description="Test Execution",
                status=status,
                files_checked=files_checked,
                files_passed=files_passed,
                files_failed=files_failed,
                errors=errors,
                duration_seconds=duration,
                metadata={
                    "tests_passed": result.get("passed", 0),
                    "tests_failed": result.get("failed", 0),
                    "tests_errors": result.get("errors", 0)
                }
            )
            
    except Exception as e:
        duration = time.time() - start_time
        logger.error(f"  Checkpoint D error: {e}")
        errors["test_execution"] = str(e)
        files_failed = files_checked
        
        return CheckpointResult(
            checkpoint_name="D",
            checkpoint_description="Test Execution",
            status=CheckpointStatus.FAILED,
            files_checked=files_checked,
            files_passed=[],
            files_failed=files_failed,
            errors=errors,
            duration_seconds=duration
        )


def verification_node(state: AgentState) -> AgentState:
    """
    Verification node - runs all verification checkpoints.
    
    Args:
        state: Current agent state
        
    Returns:
        Updated state with verification results
    """
    logger.info("=" * 60)
    logger.info("VERIFICATION NODE")
    logger.info("=" * 60)
    
    state["current_node"] = "verification"
    state["node_history"] = state.get("node_history", []) + ["verification"]
    
    generated_files = state.get("generated_files", {})
    output_path = state.get("output_path", "")
    
    if not generated_files:
        logger.warning("No generated files to verify")
        state["verification_passed"] = False
        return state
    
    # Ensure output directory exists
    os.makedirs(output_path, exist_ok=True)
    
    # Run checkpoints
    checkpoint_a = checkpoint_a_syntax(generated_files)
    logger.info(f"Checkpoint A: {checkpoint_a.status.value} ({len(checkpoint_a.files_passed)}/{len(checkpoint_a.files_checked)} passed)")
    
    checkpoint_b = checkpoint_b_imports(generated_files)
    logger.info(f"Checkpoint B: {checkpoint_b.status.value} ({len(checkpoint_b.files_passed)}/{len(checkpoint_b.files_checked)} passed)")
    
    checkpoint_c = checkpoint_c_collect(generated_files, output_path)
    logger.info(f"Checkpoint C: {checkpoint_c.status.value}")
    
    # Run Checkpoint D: Test Execution (only if A, B, C passed)
    checkpoint_d = None
    if (checkpoint_a.status == CheckpointStatus.PASSED and
        checkpoint_b.status == CheckpointStatus.PASSED and
        checkpoint_c.status == CheckpointStatus.PASSED):
        
        checkpoint_d = checkpoint_d_execution(generated_files, output_path)
        test_info = checkpoint_d.metadata.get("tests_passed", 0)
        test_failed = checkpoint_d.metadata.get("tests_failed", 0)
        logger.info(f"Checkpoint D: {checkpoint_d.status.value} ({test_info} passed, {test_failed} failed)")
    else:
        logger.info("Checkpoint D: SKIPPED (previous checkpoints failed)")
        # Create a skipped checkpoint D
        checkpoint_d = CheckpointResult(
            checkpoint_name="D",
            checkpoint_description="Test Execution",
            status=CheckpointStatus.SKIPPED,
            files_checked=[],
            files_passed=[],
            files_failed=[],
            errors={}
        )
    
    # Build verification results
    results = VerificationResults(
        checkpoint_a=checkpoint_a,
        checkpoint_b=checkpoint_b,
        checkpoint_c=checkpoint_c,
        checkpoint_d=checkpoint_d,
        all_passed=False
    )
    
    # Check if all passed (including D)
    all_passed = (
        checkpoint_a.status == CheckpointStatus.PASSED and
        checkpoint_b.status == CheckpointStatus.PASSED and
        checkpoint_c.status == CheckpointStatus.PASSED and
        checkpoint_d.status == CheckpointStatus.PASSED
    )
    results.all_passed = all_passed
    
    # Update state
    state["verification_results"] = results.model_dump()
    state["verification_passed"] = all_passed
    
    # Log summary
    logger.info("-" * 40)
    logger.info("VERIFICATION SUMMARY")
    logger.info(f"  Checkpoint A (Syntax): {checkpoint_a.status.value}")
    logger.info(f"  Checkpoint B (Imports): {checkpoint_b.status.value}")
    logger.info(f"  Checkpoint C (Collection): {checkpoint_c.status.value}")
    logger.info(f"  Checkpoint D (Execution): {checkpoint_d.status.value}")
    if checkpoint_d.metadata:
        logger.info(f"    Tests: {checkpoint_d.metadata.get('tests_passed', 0)} passed, "
                   f"{checkpoint_d.metadata.get('tests_failed', 0)} failed")
    logger.info(f"  Overall: {'PASSED' if all_passed else 'FAILED'}")
    logger.info("-" * 40)
    
    # Collect all errors for recovery
    if not all_passed:
        all_errors = {}
        for cp in [checkpoint_a, checkpoint_b, checkpoint_c, checkpoint_d]:
            if cp and cp.errors:
                all_errors.update(cp.errors)
        
        if all_errors:
            logger.warning("Errors found:")
            for filepath, error in all_errors.items():
                # Handle both string and list errors
                error_str = error if isinstance(error, str) else '\n'.join(error) if isinstance(error, list) else str(error)
                logger.warning(f"  {filepath}: {error_str[:200]}")
    
    return state
