"""Checkpoint B: Import Validation."""

import ast
import importlib.util
import logging
from typing import Dict

from ...models.schemas import CheckpointStatus, CheckpointResult

logger = logging.getLogger(__name__)


def _can_import(module_name: str) -> bool:
    """Check if a module can be imported."""
    try:
        spec = importlib.util.find_spec(module_name)
        return spec is not None
    except (ModuleNotFoundError, ValueError):
        return False


def checkpoint_b_imports(generated_files: Dict[str, str]) -> CheckpointResult:
    """
    Checkpoint B: Verify imports can be resolved.
    
    Note: This checks standard library and installed packages only.
    Internal imports between generated files are assumed valid.
    
    Args:
        generated_files: Dict of filepath -> code content
        
    Returns:
        CheckpointResult with import validation results
    """
    logger.info("Running Checkpoint B: Import Validation...")
    
    files_checked = []
    files_passed = []
    files_failed = []
    errors = {}
    
    # Known internal modules (generated by us)
    internal_modules = {"pages", "flows", "tests"}
    
    for filepath, code in generated_files.items():
        if not filepath.endswith('.py'):
            continue
        
        files_checked.append(filepath)
        file_errors = []
        
        try:
            tree = ast.parse(code)
            
            for node in ast.walk(tree):
                # Check import statements
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        module_name = alias.name.split('.')[0]
                        if module_name not in internal_modules:
                            if not _can_import(module_name):
                                file_errors.append(f"Cannot import '{alias.name}'")
                
                # Check from ... import statements
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        module_name = node.module.split('.')[0]
                        if module_name not in internal_modules:
                            if not _can_import(module_name):
                                file_errors.append(f"Cannot import from '{node.module}'")
            
            if file_errors:
                files_failed.append(filepath)
                errors[filepath] = "; ".join(file_errors)
                logger.warning(f"  ✗ {filepath}: {errors[filepath]}")
            else:
                files_passed.append(filepath)
                logger.debug(f"  ✓ {filepath}")
                
        except SyntaxError:
            # Already caught in checkpoint A
            files_passed.append(filepath)
    
    status = CheckpointStatus.PASSED if not files_failed else CheckpointStatus.FAILED
    
    return CheckpointResult(
        checkpoint_name="B",
        checkpoint_description="Import Resolution",
        status=status,
        files_checked=files_checked,
        files_passed=files_passed,
        files_failed=files_failed,
        errors=errors
    )
